import {
  IconActivity,
  IconAdjustments,
  IconAlertCircle,
  IconBolt,
  IconBriefcase,
  IconBuildingStore,
  IconCalendarTime,
  IconCategory,
  IconChartBar,
  IconChevronRight,
  IconCircleCheck,
  IconClock,
  IconDatabase,
  IconDatabaseImport,
  IconFileText,
  IconHome,
  IconMessageCircle,
  IconSettings,
  IconShieldCheck,
  type Icon,
} from "@tabler/icons-react";

export const platformIcons = {
  activity: IconActivity,
  automation: IconBolt,
  brandWorkspace: IconBuildingStore,
  category: IconCategory,
  connected: IconCircleCheck,
  data: IconDatabaseImport,
  feedback: IconMessageCircle,
  home: IconHome,
  project: IconBriefcase,
  report: IconChartBar,
  review: IconShieldCheck,
  schedule: IconCalendarTime,
  settings: IconSettings,
  statusBlocked: IconAlertCircle,
  statusInDevelopment: IconClock,
  statusReview: IconShieldCheck,
  statusComplete: IconCircleCheck,
  action: IconChevronRight,
} satisfies Record<string, Icon>;

export const categoryIcons = {
  P1: IconDatabase,
  P2: IconFileText,
  P3: IconAdjustments,
  P4: IconShieldCheck,
} satisfies Record<string, Icon>;
